theme: jekyll-theme-minimal
title: Han Dong
logo: /assets/img/profilepic.jpeg
description: Hi, you have reached my personal website. I am an Assistant Professor in the Computer Science department at Hamilton College.
