#!/bin/bash

#set -x

export MYINIT=${MYINIT:=''}
export BINS=${BINS:=''}
export LIBS=${LIBS:=''}

USAGE="Simple bash script to copy system libraries from local kernel to new initramfs, example usage:\n\nBINS=\"bash ls echo env ln mkdir mknod mount pwd umount cat head tail wc ps ip lsblk lspci lsmod halt poweroff reboot\" MYINIT=<initramfs_name> ./copy_bin_libs"

function usage() {
    echo -e $USAGE
    exit -1
}

[[ -z $BINS || -z $MYINIT ]] && usage

if [[ ! -d $MYINIT ]]; then
    echo "Folder ${MYINIT} does not exist."
    usage
fi

## function that iterates through each library
## and creates the corresponding directory
## and copy the binaries over
function copy_libs
{
    for libs in ${LIBS}; do
	libs_dir=$(dirname $libs)
	
	echo $libs
	echo $libs_dir
	
	mkdir -p "./${MYINIT}/${libs_dir}"
	cp $libs "./${MYINIT}/${libs_dir}"
    done
}

## all we do is copy the files into the proper directory in the initrd
for bins in ${BINS}; do

    echo $bins
    ## figure out where binary lives
    bins_loc=$(which $bins)
    bins_dir_loc=$(which $bins | xargs -I '{}' dirname '{}')    

    echo $bins_loc
    echo $bins_dir_loc
    
    ## set up directory tree and copy bins here
    mkdir -p "./${MYINIT}/${bins_dir_loc}"
    cp $bins_loc "./${MYINIT}/${bins_dir_loc}"

    #-------------------------------------------------------------------------#
    
    ## figure out library dependencies of $bins
    libs_loc=$(ldd $bins_loc | grep "=> /" | awk '{print $3}')
    ## set up directory tree and copy libs here
    LIBS="$libs_loc" copy_libs

    echo '#-------------------------------------------------------------------------#'


    
    ######################################
    # TODO: Uncomment incase you need to copy
    #       libraries that other libraries depend on, hopefully not too recursively messy
    #for libs in ${libs_loc}; do
    #libs_dep_loc=$(ldd $libs | grep "=> /" | awk '{print $3}')
    #LIBS="$libs_dep_loc" copy_libs
    #done
    #####################################            
done

#sudo strace -e trace=open,openat /bin/ls
