#!/bin/bash

set -x

export BINS=${BINS:=''}

## From: https://www.commandlinefu.com/commands/view/10238/copy-all-shared-libraries-for-a-binary-to-directory
## xargs is used to redirect the input from awk (which are the libraries used by the function)
## to cp in a more managed way as Linux sets a limit on filename length that can be passed
## all we do is copy the files into the proper directory in the initrd
for bins in ${BINS}; do
    #ldd /bin/ls | grep "=> /" | awk '{print $3}' | xargs -I '{}' sudo cp -v '{}' ./lib64
    ldd $bins | grep "=> /" | awk '{print $3}' | xargs -I '{}' sudo ls '{}'
    ldd $bins | grep "=> /" | awk '{print $3}' | xargs -I '{}' dirname '{}' | xargs -I '{}' mkdir -p '.{}'
done

#sudo strace -e trace=open,openat /bin/ls
